# Generated by Django 4.2.7 on 2023-12-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'contact_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUmraForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('total_persons', models.CharField(max_length=255)),
                ('total_days', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'custom_umra_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('total_persons', models.IntegerField()),
                ('childrens', models.IntegerField()),
                ('travel_start', models.DateTimeField()),
                ('travel_end', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('package_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'package_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('duration_days', models.CharField(max_length=255)),
                ('duration_nights', models.CharField(max_length=255)),
                ('inclusion', models.TextField()),
                ('room_sharing', models.CharField(max_length=255)),
                ('cities', models.CharField(max_length=255)),
                ('image1', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'packages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UmraForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('month', models.CharField(max_length=255)),
                ('departure', models.CharField(max_length=255)),
                ('total_people', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'umra_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UmraPackages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('departure', models.DateField()),
                ('arrival', models.DateField()),
                ('airlines', models.CharField(max_length=255)),
                ('hotel_makkah', models.CharField(max_length=255)),
                ('hotel_makkah_dist', models.CharField(max_length=255)),
                ('hotel_madina', models.CharField(max_length=255)),
                ('hotel_madina_dist', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'umrah_packages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('documents', models.TextField()),
                ('special_note', models.TextField()),
                ('start_price', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('flag_image', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'visa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisaDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('visa_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('start_price', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('proc_time', models.CharField(max_length=255)),
                ('stay_period', models.CharField(max_length=255)),
                ('visa_cat', models.CharField(max_length=255)),
                ('entry', models.CharField(max_length=255)),
                ('validity', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'visa_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=255)),
                ('visa_qty', models.IntegerField()),
                ('visa_country', models.CharField(max_length=255)),
                ('visa_type', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'visa_form',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
