# Generated by Django 4.2.7 on 2024-02-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0002_contactform_customumraform_packageform_packages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('visa_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('start_price', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('proc_time', models.CharField(max_length=255)),
                ('stay_period', models.CharField(max_length=255)),
                ('visa_cat', models.CharField(max_length=255)),
                ('entry', models.CharField(max_length=255)),
                ('validity', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'visa_type',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='VisaDetails',
        ),
    ]
